import threading
from datetime import date
from pathlib import Path


class Findings:
    """
    Thread-safe, live-updating writer for findings.md.

    Sections are written as they complete so the file is useful even
    mid-scan. All writes are serialised through a lock.
    """

    def __init__(self, path: Path, ip: str, domain: str | None):
        self._path = path
        self._lock = threading.Lock()
        self._write_header(ip, domain)

    # ── Public API ────────────────────────────────────────────────────────────

    def h2(self, title: str):
        self._append(f"\n## {title}\n")

    def h3(self, title: str):
        self._append(f"\n### {title}\n")

    def h4(self, title: str):
        self._append(f"\n#### {title}\n")

    def cmd(self, command: str):
        """Write the command that produced the following output."""
        self._append(f"\n> `{command}`\n")

    def bullet(self, text: str):
        self._append(f"- {text}\n")

    def note(self, text: str):
        self._append(f"\n> **Note:** {text}\n")

    def blank(self):
        self._append("\n")

    def table(self, headers: list[str], rows: list[list[str]]):
        if not rows:
            return
        col_widths = [
            max(len(h), max((len(r[i]) for r in rows), default=0))
            for i, h in enumerate(headers)
        ]
        sep = "| " + " | ".join("-" * w for w in col_widths) + " |"
        header_row = "| " + " | ".join(h.ljust(col_widths[i]) for i, h in enumerate(headers)) + " |"
        lines = ["\n", header_row, sep]
        for row in rows:
            lines.append("| " + " | ".join(str(row[i]).ljust(col_widths[i]) for i in range(len(headers))) + " |")
        self._append("\n".join(lines) + "\n")

    def code_block(self, content: str, lang: str = ""):
        if content.strip():
            self._append(f"\n```{lang}\n{content.rstrip()}\n```\n")

    def raw_section(self, title: str, command: str, content: str):
        """Convenience: write a titled subsection with command + content."""
        self.h4(title)
        self.cmd(command)
        if content.strip():
            self.code_block(content)

    def finalize(self):
        self._append("\n---\n*Generated by p0rtix*\n")

    # ── Internal ──────────────────────────────────────────────────────────────

    def _write_header(self, ip: str, domain: str | None):
        domain_line = f"**Domain:** {domain}  \n" if domain else ""
        header = (
            f"# p0rtix — {ip}\n\n"
            f"**Date:** {date.today()}  \n"
            f"**Target:** {ip}  \n"
            f"{domain_line}\n"
            "---\n"
        )
        self._path.write_text(header)

    def _append(self, text: str):
        with self._lock:
            with self._path.open("a") as fh:
                fh.write(text)
